# DL Hyperparameter Tuning and Training Pipeline
#
# A Github Service Connection must also be created with the name "AIArchitecturesAndPractices-GitHub"

resources:
  repositories:
    - repository: aitemplates
      type: github
      name: microsoft/AI
      endpoint: AIArchitecturesAndPractices-GitHub

trigger:
  batch: true
  branches:
    include:
    - mabou/instrument

stages:
- template: .ci/stages/deploy_notebooks_stages_v2.yml@aitemplates
  parameters:
    Agent: $(Agent_Name)
    Demands: GPU
    jobDisplayName: DLBatchDeployJob
    DefaultWorkingDirectory: $(System.DefaultWorkingDirectory)
    workload_vars: ../vars/dl_batch_scoring.yml
